import { format } from "date-fns";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, BorderStyle } from "docx";
import { jsPDF } from "jspdf";

// Clean content by removing markdown-style formatting
export function cleanContent(content: string): string {
  return content
    // Remove ** bold markers
    .replace(/\*\*(.*?)\*\*/g, "$1")
    // Remove * italic markers
    .replace(/\*(.*?)\*/g, "$1")
    // Remove # headings, convert to plain text with line breaks
    .replace(/^#{1,6}\s+(.*)$/gm, "\n$1\n")
    // Remove --- horizontal rules
    .replace(/^-{3,}$/gm, "\n")
    // Remove bullet points formatting but keep structure
    .replace(/^[\-\*]\s+/gm, "• ")
    // Clean up multiple line breaks
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

// Generate proper filename
export function generateFilename(
  classLevel: string | null,
  subject: string | null,
  type: "Syllabus" | "Quiz" | "LessonPlan"
): string {
  const date = format(new Date(), "yyyy-MM-dd");
  const className = classLevel ? `Class${classLevel}` : "General";
  const subjectName = subject?.replace(/\s+/g, "") || "General";
  return `${className}_${subjectName}_${type}_${date}`;
}

// Download as TXT
export function downloadAsTxt(
  content: string,
  classLevel: string | null,
  subject: string | null,
  type: "Syllabus" | "Quiz" | "LessonPlan",
  title?: string
): void {
  const cleanedContent = cleanContent(content);
  const filename = generateFilename(classLevel, subject, type);
  
  const header = title || `${type} - ${subject || "General"} - Class ${classLevel || "All"}`;
  const date = format(new Date(), "MMMM dd, yyyy");
  
  const textContent = `${header}\nGenerated on: ${date}\n${"=".repeat(60)}\n\n${cleanedContent}\n\n${"=".repeat(60)}\nGenerated by TeachAI Assistant\n`;

  const blob = new Blob([textContent], { type: "text/plain;charset=utf-8" });
  downloadBlob(blob, `${filename}.txt`);
}

// Download as proper DOCX
export async function downloadAsDocx(
  content: string,
  classLevel: string | null,
  subject: string | null,
  type: "Syllabus" | "Quiz" | "LessonPlan",
  title?: string
): Promise<void> {
  const cleanedContent = cleanContent(content);
  const filename = generateFilename(classLevel, subject, type);
  
  const header = title || `${type} - ${subject || "General"} - Class ${classLevel || "All"}`;
  const date = format(new Date(), "MMMM dd, yyyy");

  // Parse content into paragraphs
  const lines = cleanedContent.split("\n");
  const paragraphs: Paragraph[] = [];

  // Add title
  paragraphs.push(
    new Paragraph({
      children: [
        new TextRun({
          text: header,
          bold: true,
          size: 36,
          color: "1e40af",
        }),
      ],
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
    })
  );

  // Add date
  paragraphs.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated on: ${date}`,
          italics: true,
          size: 22,
          color: "64748b",
        }),
      ],
      spacing: { after: 400 },
      border: {
        bottom: {
          color: "3b82f6",
          size: 12,
          style: BorderStyle.SINGLE,
          space: 8,
        },
      },
    })
  );

  // Add content lines
  for (const line of lines) {
    if (line.trim() === "") {
      paragraphs.push(new Paragraph({ spacing: { after: 100 } }));
    } else {
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: line,
              size: 24,
            }),
          ],
          spacing: { after: 120 },
        })
      );
    }
  }

  // Add footer
  paragraphs.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "Generated by TeachAI Assistant",
          italics: true,
          size: 18,
          color: "94a3b8",
        }),
      ],
      spacing: { before: 400 },
    })
  );

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: paragraphs,
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  downloadBlob(blob, `${filename}.docx`);
}

// Download as proper PDF
export function downloadAsPdf(
  content: string,
  classLevel: string | null,
  subject: string | null,
  type: "Syllabus" | "Quiz" | "LessonPlan",
  title?: string
): void {
  const cleanedContent = cleanContent(content);
  const filename = generateFilename(classLevel, subject, type);
  
  const header = title || `${type} - ${subject || "General"} - Class ${classLevel || "All"}`;
  const date = format(new Date(), "MMMM dd, yyyy");
  
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Add title
  doc.setFontSize(20);
  doc.setTextColor(30, 64, 175); // Blue color
  doc.setFont("helvetica", "bold");
  const titleLines = doc.splitTextToSize(header, contentWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 8 + 5;

  // Add date
  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139); // Gray color
  doc.setFont("helvetica", "italic");
  doc.text(`Generated on: ${date}`, margin, y);
  y += 8;

  // Add separator line
  doc.setDrawColor(59, 130, 246); // Blue color
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Add content
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59); // Dark color
  doc.setFont("helvetica", "normal");

  const lines = doc.splitTextToSize(cleanedContent, contentWidth);
  
  for (let i = 0; i < lines.length; i++) {
    if (y > pageHeight - margin - 15) {
      doc.addPage();
      y = margin;
    }
    doc.text(lines[i], margin, y);
    y += 5;
  }

  // Add footer on last page
  y = pageHeight - margin;
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.setFont("helvetica", "italic");
  doc.text("Generated by TeachAI Assistant", pageWidth / 2, y, { align: "center" });

  // Save the PDF
  doc.save(`${filename}.pdf`);
}

// Helper to trigger download
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
