import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Get user from token
    const token = authHeader.replace("Bearer ", "");
    const { data: { user }, error: userError } = await supabase.auth.getUser(token);
    
    if (userError || !user) {
      return new Response(JSON.stringify({ error: "Invalid token" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const body = await req.json();
    const { content, title, format = "txt", type = "syllabus" } = body;

    if (!content) {
      return new Response(JSON.stringify({ error: "No content provided" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Generate file content based on format
    let fileContent: Blob;
    let fileName: string;
    let contentType: string;

    if (format === "pdf") {
      // Create a simple HTML-to-PDF-like text document
      // For proper PDF generation, you'd need a library like PDFKit
      // For now, we'll create a text file with .pdf extension that contains the content
      const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title || type}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; line-height: 1.6; }
    h1 { color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }
    h2 { color: #555; margin-top: 20px; }
    .content { white-space: pre-wrap; }
    .footer { margin-top: 40px; border-top: 1px solid #ccc; padding-top: 10px; color: #888; font-size: 12px; }
  </style>
</head>
<body>
  <h1>${title || (type === 'syllabus' ? 'Lesson Plan' : 'Quiz')}</h1>
  <div class="content">${content.replace(/\n/g, '<br>')}</div>
  <div class="footer">Generated by TeachAI on ${new Date().toLocaleDateString()}</div>
</body>
</html>`;
      fileContent = new Blob([htmlContent], { type: "text/html" });
      fileName = `${type}_${Date.now()}.html`;
      contentType = "text/html";
    } else if (format === "docx") {
      // Create a simple XML-based document
      // For proper DOCX, you'd need a library like docx
      const docContent = `<?xml version="1.0" encoding="UTF-8"?>
<document>
  <title>${title || type}</title>
  <content>${content}</content>
  <generated>${new Date().toISOString()}</generated>
</document>`;
      fileContent = new Blob([docContent], { type: "application/xml" });
      fileName = `${type}_${Date.now()}.xml`;
      contentType = "application/xml";
    } else {
      // Plain text
      const textContent = `${title || (type === 'syllabus' ? 'Lesson Plan' : 'Quiz')}
${'='.repeat(50)}

${content}

---
Generated by TeachAI on ${new Date().toLocaleDateString()}`;
      fileContent = new Blob([textContent], { type: "text/plain" });
      fileName = `${type}_${Date.now()}.txt`;
      contentType = "text/plain";
    }

    // Upload to storage
    const storagePath = `${user.id}/${fileName}`;
    const { error: uploadError } = await supabase.storage
      .from("generated-files")
      .upload(storagePath, fileContent, {
        contentType,
        upsert: true,
      });

    if (uploadError) {
      console.error("Upload error:", uploadError);
      return new Response(JSON.stringify({ error: "Failed to upload file" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Get public URL
    const { data: { publicUrl } } = supabase.storage
      .from("generated-files")
      .getPublicUrl(storagePath);

    return new Response(
      JSON.stringify({ 
        success: true,
        fileUrl: publicUrl,
        fileName,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Generate document error:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
